### ISSUE TITLE
OpenXR support

### ISSUE THREAD

**Issue by jacklul** [fholger/vrperfkit#17]
Any plans for this?

**Comment by fholger** [comment]
Not sure. OpenXR support is a bit tricky because you are technically supposed to use layers instead of injection to implement custom functionality like this. Doing it with injection might be awkward and prone to break. But layers don't really fit well into my architecture, and they are not very user-friendly. Given that the number of games using OpenXR is incredibly small, this has the lowest possible priority for me right now :)

Besides, for upscaling with OpenXR, there's already this: https://github.com/mbucchia/OpenXR-Toolkit

**Comment by DJSlane** [comment]
Man - shoot!  The open Xr thing from this guy seems to BREAK the AA from the game. Does that make sense? I tried repeatedly to use the app above (now updated for NIS or FSR) and I just can't appreciate what happens. I hear DLSS is coming to FS2020 though. If it works in VR that'd be great! (Will it work in VR?) All I can say is DLSS works honestly very well for CyberPunk and Red Dead Redemption 2 - I was a DLSS skeptic until I saw my frame rate...

**Comment by DrDukester** [comment]
For WMR users it would be great to have a solution to bypass steamvr. 
https://old.reddit.com/r/HPReverb/comments/lo2s11/wmr_devs_identify_performance_bottleneck_between/ 

Here is a project of an openvr_api.dll which gives openxr for wmr headsets, bypassing steam vr. There is probably some headroom performance wise but the headset (HP G2) behaves much more like a monitor - when the frame rate is below the refresh rate the picture is a lot more fluid than with steam vr.  For WMR headset users this would be a game changer :)
https://www.assettocorsa.net/forum/index.php?threads/openxr-for-wmr.70825/

**Comment by fholger** [comment]
I can't help you with that. Writing a SteamVR to OpenXR wrapper is way out of scope for this project.

**Comment by fholger** [comment]
Given that the OpenXR toolkit now pretty much supports everything that vrperfkit does, but for OpenXR, I see no incentive to add OpenXR support to vrperfkit.
