### ISSUE TITLE
Iracing won't close session

### ISSUE THREAD

**Issue by g3raid** [fholger/vrperfkit#70]
After a practice run or race and trying to start a new session. I get an error message that says. Iracing is already running. After forceclosing iracing via task manager it works again.
I am running an valve index trough steamvr.

**Comment by shiznat** [comment]
Same issue here, iRacing seems to never end the process fully while using this mod. Force closing through task manager fixes it.

**Comment by SuperUniqueName** [comment]
Same issue here as well. Hopefully it's an easy fix and someone can figure it out.

**Comment by Scotchy49** [comment]
I believe this is an iRacing issue as it happens without vrperfkit as well.

when you exit an iRacing session, the sim keeps running for some time in the background.
Trying to run another session before the sim has had time to shutdown completely will deadlock the UI into a “sim loading…” state.

The fix is to wait until the iRacing Simulator process has terminated.

**Comment by g3raid** [comment]
Thanks for the information. As it is not an vrperfkit issue. I will close this issue
